apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-west-2

iam:
  withOIDC: true

nodeGroups:
  - name: demo-app
    instanceType: t3.micro
    amiFamily: AmazonLinux2
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: udapeople
